version: '3'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        networks:
            - applicationnetwork
    application:
        build:
            context: ./application
        image: mateus21/application-image
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s node index.js
        container_name: application
        restart: always
        tty: true
        networks:
            - applicationnetwork
        depends_on:
            - mysql
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        tty: true
        ports:
            - "8080:80"
        networks:
            - applicationnetwork
        depends_on:
            - application

networks:
    applicationnetwork:
        driver: bridge