version: '3'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        container_name: mysql
        networks:
            - xptonet
        ports:
            - "3306:3306"

networks:
    xptonet:
        driver: bridge